export default function Home() {
  return (
    <div>
      <>
        <title>Trade-Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <div className="text-3xl text-center font-bold font-Raleway">
          Hello World !
        </div>
      </>
    </div>
  );
}
